services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && gunicorn cinema_service.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/cinema
volumes:
  postgres_data:
