services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/cinema
volumes:
  postgres_data:
